emacsの設定ファイルを、初期化・設定ファイルとelispとに分割する

diff --git a/.zsh/modules/auto-fu/auto-fu b/.zsh/modules/auto-fu/auto-fu
--- a/.zsh/modules/auto-fu/auto-fu
+++ b/.zsh/modules/auto-fu/auto-fu
@@ -29,58 +29,6 @@ afu+accept-line () {
 	zstyle -T ':auto-fu:var' postdisplay/clearp && POSTDISPLAY='' 
 	return 0
 }
-afu+cancel () {
-	afu-clearing-maybe
-	((afu_in_p == 1)) && {
-		afu_in_p=0 
-		BUFFER="$buffer_cur" 
-	}
-}
-kill-whole-line-by-keymap () {
-	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
-	then
-		zle $KEYMAP+$WIDGET "$@"
-	else
-		zle .$WIDGET "$@"
-	fi
-}
-afu-reset () {
-	region_highlight=() 
-	afu_in_p=0 
-	local ps
-	zstyle -s ':auto-fu:var' postdisplay ps
-	[[ -z ${ps} ]] || POSTDISPLAY='' 
-}
-afu-clean () {
-	local d=${1:-~/.zsh}
-	trash-put -f ${d}/{auto-fu,auto-fu.zwc*(N)}
-}
-yank-by-keymap () {
-	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
-	then
-		zle $KEYMAP+$WIDGET "$@"
-	else
-		zle .$WIDGET "$@"
-	fi
-}
-afu+yank () {
-	with-afu .yank self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-auto-fu-off () {
-	with-afu-gvars zle -K emacs
-}
-auto-fu-on () {
-	with-afu-gvars zle -K afu
-}
-afu+orf-ignoreeof-deletechar-list () {
-	afu-eof-maybe afu-ignore-eof zle delete-char-or-list
-}
-afu-ad-delete-unambiguous-prefix () {
-	local afufun="$1"
-	local code
-	code=$functions[$afufun] 
-	eval "function $afufun () { zle afu+delete-unambiguous-prefix; $code }"
-}
 afu-comppost () {
 	((compstate[list_lines] + BUFFERLINES + 2 > LINES)) && {
 		compstate[list]='' 
@@ -88,6 +36,9 @@ afu-comppost () {
 	}
 	typeset -g afu_one_match_p=
 	(( $compstate[nmatches] == 1 )) && afu_one_match_p=t 
+}
+afu+vi-ins-mode () {
+	zle -K afu
 }
 auto-fu () {
 	emulate -L zsh
@@ -141,6 +92,22 @@ auto-fu-init () {
 		[[ -z ${ps} ]] || POSTDISPLAY='' 
 	}
 }
+afu-install-eof () {
+	zstyle -t ':auto-fu:var' eof-installed-p || {
+		if [[ "$options[ignoreeof]" = "on" ]]
+		then
+			bindkey "^D" afu+orf-ignoreeof-deletechar-list
+		else
+			setopt ignoreeof
+			bindkey "^D" afu+orf-exit-deletechar-list
+		fi
+	} always {
+		zstyle ':auto-fu:var' eof-installed-p yes
+	}
+}
+afu+vi-cmd-mode () {
+	zle -K afu-vicmd
+}
 afu+accept-line-and-down-history () {
 	__accepted=($WIDGET ${=NUMERIC:+-n $NUMERIC} "$@") 
 	zle .accept-line-and-down-history && {
@@ -150,207 +117,6 @@ afu+accept-line-and-down-history () {
 	}
 	zstyle -T ':auto-fu:var' postdisplay/clearp && POSTDISPLAY='' 
 	return 0
-}
-afu-able-p () {
-	(( afu_paused_p == 1 )) && return 1
-	local c=$LBUFFER[-1]
-	[[ $c = '' ]] && return 1
-	[[ $c = ' ' ]] && {
-		afu-able-space-p || return 1 && return 0
-	}
-	[[ $c = '.' ]] && return 1
-	[[ $c = '^' ]] && return 1
-	[[ $c = '~' ]] && return 1
-	[[ $c = ')' ]] && return 1
-	return 0
-}
-with-afu-compfuncs () {
-	compprefuncs=(afu-comppre) 
-	comppostfuncs=(afu-comppost) 
-	"$@"
-}
-self-insert-by-keymap () {
-	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
-	then
-		zle $KEYMAP+$WIDGET "$@"
-	else
-		zle .$WIDGET "$@"
-	fi
-}
-afu+kill-line () {
-	with-afu .kill-line self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-auto-fu-toggle () {
-	(( afu_paused_p == 1 )) && {
-		afu_paused_p=0 
-		return
-	}
-	(( afu_paused_p != 1 )) && {
-		afu_paused_p=1 
-		return
-	}
-}
-kill-word-by-keymap () {
-	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
-	then
-		zle $KEYMAP+$WIDGET "$@"
-	else
-		zle .$WIDGET "$@"
-	fi
-}
-auto-fu-maybe () {
-	(($PENDING== 0)) && {
-		afu-able-p
-	} && [[ $LBUFFER != *$'
-'* ]] && {
-		auto-fu
-	}
-}
-afu-install () {
-	zstyle -t ':auto-fu:var' misc-installed-p || {
-		zmodload zsh/parameter 2> /dev/null || {
-			echo 'auto-fu:zmodload error. exiting.' >&2
-			exit -1
-		}
-		afu-install-isearchmap
-		afu-install-eof
-	} always {
-		zstyle ':auto-fu:var' misc-installed-p yes
-	}
-	bindkey -N afu emacs
-	{
-		"$@"
-	}
-	bindkey -M afu "^I" afu+complete-word
-	bindkey -M afu "^M" afu+accept-line
-	bindkey -M afu "^J" afu+accept-line
-	bindkey -M afu "^O" afu+accept-line-and-down-history
-	bindkey -M afu "^[a" afu+accept-and-hold
-	bindkey -M afu "^X^[" afu+vi-cmd-mode
-	bindkey -N afu-vicmd vicmd
-	bindkey -M afu-vicmd "i" afu+vi-ins-mode
-}
-afu+magic-space () {
-	with-afu .magic-space self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-auto-fu-install () {
-	{
-		zle -N afu+accept-and-hold
-		zle -N afu+accept-line
-		zle -N afu+accept-line-and-down-history
-		zle -N afu+backward-delete-char
-		zle -N afu+backward-kill-word
-		zle -N afu+cancel
-		zle -N afu+cancel-afu+accept-line
-		zle -N afu+cancel-send-break
-		zle -N afu+complete-word
-		zle -N afu+delete-unambiguous-prefix
-		zle -N afu+kill-line
-		zle -N afu+kill-whole-line
-		zle -N afu+kill-word
-		zle -N afu+magic-space
-		zle -N afu+orf-exit-deletechar-list
-		zle -N afu+orf-ignoreeof-deletechar-list
-		zle -N afu+self-insert
-		zle -N afu+vi-cmd-mode
-		zle -N afu+vi-ins-mode
-		zle -N afu+yank
-		zle -N auto-fu
-		zle -N auto-fu-activate
-		zle -N auto-fu-deactivate
-		zle -N auto-fu-init
-		zle -N auto-fu-off
-		zle -N auto-fu-on
-		zle -N auto-fu-toggle
-		zle -N self-insert self-insert-by-keymap
-		zle -N backward-delete-char backward-delete-char-by-keymap
-		zle -N backward-kill-word backward-kill-word-by-keymap
-		zle -N kill-line kill-line-by-keymap
-		zle -N kill-whole-line kill-whole-line-by-keymap
-		zle -N kill-word kill-word-by-keymap
-		zle -N magic-space magic-space-by-keymap
-		zle -N yank yank-by-keymap
-		zle -N afu+self-insert
-		zle -N afu+backward-delete-char
-		zle -N afu+backward-kill-word
-		zle -N afu+kill-line
-		zle -N afu+kill-whole-line
-		zle -N afu+kill-word
-		zle -N afu+magic-space
-		zle -N afu+yank
-	}
-	afu-install
-	typeset -ga afu_accept_lines
-	afu_accept_lines=(afu+accept-line afu+accept-line-and-down-history afu+accept-and-hold) 
-}
-auto-fu-deactivate () {
-	afu_paused_p=1 
-}
-afu+backward-kill-word () {
-	with-afu .backward-kill-word self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-afu+delete-unambiguous-prefix () {
-	afu-clearing-maybe
-	local buf
-	buf="$BUFFER" 
-	local bufc
-	bufc="$buffer_cur" 
-	[[ -z "$cursor_new" ]] && cursor_new=-1 
-	[[ "$buf[$cursor_new]" = ' ' ]] && return
-	[[ "$buf[$cursor_new]" = '/' ]] && return
-	((afu_in_p == 1)) && [[ "$buf" != "$bufc" ]] && {
-		zle afu+complete-word
-		[[ "$buf" = "$BUFFER" ]] && {
-			afu_in_p=0 
-			buf="$bufc" 
-		}
-		BUFFER="$buf" 
-		buffer_cur="$bufc" 
-	}
-}
-afu+self-insert () {
-	with-afu .self-insert self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-afu-able-space-p () {
-	[[ -z ${AUTO_FU_NOCP-} ]] && {
-		[[ "$WIDGET" = "magic-space" ]] || return 1
-	}
-	local -a x
-	: ${(A)x::=${(z)LBUFFER}}
-	[[ $x[1] != man ]]
-}
-afu+kill-whole-line () {
-	with-afu .kill-whole-line self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-magic-space-by-keymap () {
-	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
-	then
-		zle $KEYMAP+$WIDGET "$@"
-	else
-		zle .$WIDGET "$@"
-	fi
-}
-afu-eof-maybe () {
-	local eof="$1"
-	shift
-	[[ "$BUFFER" != '' ]] || {
-		$eof
-		return
-	}
-	"$@"
-}
-afu-comppre () {
-	
-}
-afu+cancel-afu+accept-line () {
-	zle afu+cancel
-	zle afu+accept-line
-}
-afu+vi-ins-mode () {
-	zle -K afu
-}
-afu+vi-cmd-mode () {
-	zle -K afu-vicmd
 }
 afu+complete-word () {
 	afu-clearing-maybe
@@ -393,6 +159,65 @@ afu+complete-word () {
 		zle complete-word
 	fi
 }
+kill-whole-line-by-keymap () {
+	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
+	then
+		zle $KEYMAP+$WIDGET "$@"
+	else
+		zle .$WIDGET "$@"
+	fi
+}
+afu-able-p () {
+	(( afu_paused_p == 1 )) && return 1
+	local c=$LBUFFER[-1]
+	[[ $c = '' ]] && return 1
+	[[ $c = ' ' ]] && {
+		afu-able-space-p || return 1 && return 0
+	}
+	[[ $c = '.' ]] && return 1
+	[[ $c = '^' ]] && return 1
+	[[ $c = '~' ]] && return 1
+	[[ $c = ')' ]] && return 1
+	return 0
+}
+afu-clean () {
+	local d=${1:-~/.zsh}
+	rm -f ${d}/{auto-fu,auto-fu.zwc*(N)}
+}
+afu+orf-exit-deletechar-list () {
+	afu-eof-maybe exit zle delete-char-or-list
+}
+afu-reset () {
+	region_highlight=() 
+	afu_in_p=0 
+	local ps
+	zstyle -s ':auto-fu:var' postdisplay ps
+	[[ -z ${ps} ]] || POSTDISPLAY='' 
+}
+backward-kill-word-by-keymap () {
+	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
+	then
+		zle $KEYMAP+$WIDGET "$@"
+	else
+		zle .$WIDGET "$@"
+	fi
+}
+yank-by-keymap () {
+	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
+	then
+		zle $KEYMAP+$WIDGET "$@"
+	else
+		zle .$WIDGET "$@"
+	fi
+}
+auto-fu-activate () {
+	afu_paused_p=0 
+}
+with-afu-compfuncs () {
+	compprefuncs=(afu-comppre) 
+	comppostfuncs=(afu-comppost) 
+	"$@"
+}
 afu-recursive-edit-and-accept () {
 	local -a __accepted
 	zle recursive-edit -K afu || {
@@ -407,8 +232,53 @@ afu-recursive-edit-and-accept () {
 		zle accept-line
 	}
 }
+afu+kill-line () {
+	with-afu .kill-line self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
+self-insert-by-keymap () {
+	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
+	then
+		zle $KEYMAP+$WIDGET "$@"
+	else
+		zle .$WIDGET "$@"
+	fi
+}
+afu+yank () {
+	with-afu .yank self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
 afu+kill-word () {
 	with-afu .kill-word self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
+auto-fu-toggle () {
+	(( afu_paused_p == 1 )) && {
+		afu_paused_p=0 
+		return
+	}
+	(( afu_paused_p != 1 )) && {
+		afu_paused_p=1 
+		return
+	}
+}
+afu+backward-delete-char () {
+	with-afu .backward-delete-char self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
+kill-word-by-keymap () {
+	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
+	then
+		zle $KEYMAP+$WIDGET "$@"
+	else
+		zle .$WIDGET "$@"
+	fi
+}
+with-afu-gvars () {
+	(( auto_fu_init_p == 1 )) && {
+		zle -M "Sorry, can't turn on or off if auto-fu-init is in effect."
+		return
+	}
+	typeset -g afu_in_p=0
+	typeset -g afu_paused_p=0
+	region_highlight=() 
+	"$@"
 }
 with-afu () {
 	local zlefun="$1"
@@ -434,6 +304,9 @@ with-afu () {
 		auto-fu-maybe
 	}
 }
+auto-fu-off () {
+	with-afu-gvars zle -K emacs
+}
 afu-clearing-maybe () {
 	region_highlight=() 
 	if ((afu_in_p == 1))
@@ -443,8 +316,105 @@ afu-clearing-maybe () {
 		}
 	fi
 }
+auto-fu-on () {
+	with-afu-gvars zle -K afu
+}
+auto-fu-maybe () {
+	(($PENDING== 0)) && {
+		afu-able-p
+	} && [[ $LBUFFER != *$'
+'* ]] && {
+		auto-fu
+	}
+}
+afu-install () {
+	zstyle -t ':auto-fu:var' misc-installed-p || {
+		zmodload zsh/parameter 2> /dev/null || {
+			echo 'auto-fu:zmodload error. exiting.' >&2
+			exit -1
+		}
+		afu-install-isearchmap
+		afu-install-eof
+	} always {
+		zstyle ':auto-fu:var' misc-installed-p yes
+	}
+	bindkey -N afu emacs
+	{
+		"$@"
+	}
+	bindkey -M afu "^I" afu+complete-word
+	bindkey -M afu "^M" afu+accept-line
+	bindkey -M afu "^J" afu+accept-line
+	bindkey -M afu "^O" afu+accept-line-and-down-history
+	bindkey -M afu "^[a" afu+accept-and-hold
+	bindkey -M afu "^X^[" afu+vi-cmd-mode
+	bindkey -N afu-vicmd vicmd
+	bindkey -M afu-vicmd "i" afu+vi-ins-mode
+}
+afu+magic-space () {
+	with-afu .magic-space self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
 afu-ignore-eof () {
 	zle -M "zsh: use 'exit' to exit."
+}
+auto-fu-install () {
+	{
+		zle -N afu+accept-and-hold
+		zle -N afu+accept-line
+		zle -N afu+accept-line-and-down-history
+		zle -N afu+backward-delete-char
+		zle -N afu+backward-kill-word
+		zle -N afu+complete-word
+		zle -N afu+kill-line
+		zle -N afu+kill-whole-line
+		zle -N afu+kill-word
+		zle -N afu+magic-space
+		zle -N afu+orf-exit-deletechar-list
+		zle -N afu+orf-ignoreeof-deletechar-list
+		zle -N afu+self-insert
+		zle -N afu+vi-cmd-mode
+		zle -N afu+vi-ins-mode
+		zle -N afu+yank
+		zle -N auto-fu
+		zle -N auto-fu-activate
+		zle -N auto-fu-deactivate
+		zle -N auto-fu-init
+		zle -N auto-fu-off
+		zle -N auto-fu-on
+		zle -N auto-fu-toggle
+		zle -N self-insert self-insert-by-keymap
+		zle -N backward-delete-char backward-delete-char-by-keymap
+		zle -N backward-kill-word backward-kill-word-by-keymap
+		zle -N kill-line kill-line-by-keymap
+		zle -N kill-whole-line kill-whole-line-by-keymap
+		zle -N kill-word kill-word-by-keymap
+		zle -N magic-space magic-space-by-keymap
+		zle -N yank yank-by-keymap
+		zle -N afu+self-insert
+		zle -N afu+backward-delete-char
+		zle -N afu+backward-kill-word
+		zle -N afu+kill-line
+		zle -N afu+kill-whole-line
+		zle -N afu+kill-word
+		zle -N afu+magic-space
+		zle -N afu+yank
+	}
+	afu-install
+	typeset -ga afu_accept_lines
+	afu_accept_lines=(afu+accept-line afu+accept-line-and-down-history afu+accept-and-hold) 
+}
+afu+backward-kill-word () {
+	with-afu .backward-kill-word self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
+auto-fu-deactivate () {
+	afu_paused_p=1 
+}
+afu-install-isearchmap () {
+	zstyle -t ':auto-fu:var' isearchmap-installed-p || {
+		[[ -n ${(M)keymaps:#isearch} ]] && bindkey -M isearch "^M" afu+accept-line
+	} always {
+		zstyle ':auto-fu:var' isearchmap-installed-p yes
+	}
 }
 kill-line-by-keymap () {
 	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
@@ -454,27 +424,24 @@ kill-line-by-keymap () {
 		zle .$WIDGET "$@"
 	fi
 }
-afu+cancel-send-break () {
-	zle afu+cancel
-	zle send-break
+afu+orf-ignoreeof-deletechar-list () {
+	afu-eof-maybe afu-ignore-eof zle delete-char-or-list
 }
-afu-install-eof () {
-	zstyle -t ':auto-fu:var' eof-installed-p || {
-		if [[ "$options[ignoreeof]" = "on" ]]
-		then
-			bindkey "^D" afu+orf-ignoreeof-deletechar-list
-		else
-			setopt ignoreeof
-			bindkey "^D" afu+orf-exit-deletechar-list
-		fi
-	} always {
-		zstyle ':auto-fu:var' eof-installed-p yes
+afu-able-space-p () {
+	[[ -z ${AUTO_FU_NOCP-} ]] && {
+		[[ "$WIDGET" = "magic-space" ]] || return 1
 	}
+	local -a x
+	: ${(A)x::=${(z)LBUFFER}}
+	[[ $x[1] != man ]]
 }
-afu+orf-exit-deletechar-list () {
-	afu-eof-maybe exit zle delete-char-or-list
+afu+self-insert () {
+	with-afu .self-insert self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
 }
-backward-kill-word-by-keymap () {
+afu+kill-whole-line () {
+	with-afu .kill-whole-line self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
+}
+magic-space-by-keymap () {
 	if (( $+widgets[$KEYMAP+$WIDGET] == 1 ))
 	then
 		zle $KEYMAP+$WIDGET "$@"
@@ -482,26 +449,15 @@ backward-kill-word-by-keymap () {
 		zle .$WIDGET "$@"
 	fi
 }
-auto-fu-activate () {
-	afu_paused_p=0 
-}
-afu+backward-delete-char () {
-	with-afu .backward-delete-char self-insert backward-delete-char backward-kill-word kill-line kill-whole-line kill-word magic-space yank
-}
-with-afu-gvars () {
-	(( auto_fu_init_p == 1 )) && {
-		zle -M "Sorry, can't turn on or off if auto-fu-init is in effect."
+afu-eof-maybe () {
+	local eof="$1"
+	shift
+	[[ "$BUFFER" != '' ]] || {
+		$eof
 		return
 	}
-	typeset -g afu_in_p=0
-	typeset -g afu_paused_p=0
-	region_highlight=() 
 	"$@"
 }
-afu-install-isearchmap () {
-	zstyle -t ':auto-fu:var' isearchmap-installed-p || {
-		[[ -n ${(M)keymaps:#isearch} ]] && bindkey -M isearch "^M" afu+accept-line
-	} always {
-		zstyle ':auto-fu:var' isearchmap-installed-p yes
-	}
+afu-comppre () {
+	
 }
